[ERROR] 2021-06-30 14:56:11,357 __main__ <ipython-input-7-c78f3cbb8272>:4 페이지를 찾을 수 없습니다. (logging_example)
[ERROR] 2021-06-30 14:56:11,434 __main__ <ipython-input-7-c78f3cbb8272>:9 요청 중에 예외가 발생했습니다: MissingSchema("Invalid URL '#invalid_url': No schema supplied. Perhaps you meant http://#invalid_url?") (logging_example)
Traceback (most recent call last):
  File "<ipython-input-7-c78f3cbb8272>", line 7, in logging_example
    r = requests.get('#invalid_url', timeout=1)
  File "C:\Users\i\anaconda3\envs\django\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\i\anaconda3\envs\django\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\i\anaconda3\envs\django\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\i\anaconda3\envs\django\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Users\i\anaconda3\envs\django\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\i\anaconda3\envs\django\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '#invalid_url': No schema supplied. Perhaps you meant http://#invalid_url?
